include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/bamcount.smk"
include: "rules/cram_archive.smk"
include: "rules/extract_jx.smk"
include: "rules/fair_fastqc_multiqc.smk"
include: "rules/fastq_check.smk"
include: "rules/feature_count.smk"
include: "rules/sort.smk"


rule target:
    input:
        **get_targets(),
